// <auto-generated />
namespace Map.Business.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lend : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lend));
        
        string IMigrationMetadata.Id
        {
            get { return "201607111024402_lend"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
