// <auto-generated />
namespace MapLend.Mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeviewmodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeviewmodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201607180812054_remove view models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
